# Generated by Django 4.2.13 on 2025-07-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_room_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_toxic',
            field=models.BooleanField(default=False),
        ),
    ]
