# Generated by Django 4.2.13 on 2025-07-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_message_is_toxic'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
